services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: WebDockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./htdocs:/var/www/html
      - ./simplon-php:/var/www/simplon-php
    environment:
      SIMPLONPHP_DIR: /var/www/simplon-php
      DB_HOST: db
      DB_USER: root
      DB_PASS: ""

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
